// Works out which image(s) a place can show. Sources, in priority order:
//
//   1. Admin override    — a Google Drive link pasted on the /admin page
//                          (stored in this browser only, see adminImages.js)
//   2. Local image file  — any file in src/assets/places/ whose name starts
//                          with the place_id:  635.jpg  or  635_pangong-lake.jpg
//   3. External URL      — an entry in src/data/placeImages.json
//                          ({ "635": "https://..." }), e.g. generated by
//                          scripts/fetch_wikipedia_images.py
//
// If none of them exist (or they fail to load) <PlaceImage> shows a
// coloured placeholder, so cards never look broken.
import externalUrls from "../data/placeImages.json";
import { getImage as getAdminImage } from "../api/adminImages.js";

// Vite resolves this at build time; when the folder is empty it is just {}.
const localFiles = import.meta.glob("../assets/places/*.{jpg,jpeg,png,webp,avif}", {
  eager: true,
  query: "?url",
  import: "default",
});

const localById = {};
for (const [path, url] of Object.entries(localFiles)) {
  const fileName = path.split("/").pop();
  const match = fileName.match(/^(\d+)(?:[_-].*)?\.[a-z0-9]+$/i);
  if (match) localById[Number(match[1])] = url;
}

export function getPlaceImageSources(place) {
  const id = place.place_id;
  return [getAdminImage(id), localById[id], externalUrls[id]].filter(Boolean);
}

export function countPlacesWithBundledImage(places) {
  return places.filter((p) => localById[p.place_id] || externalUrls[p.place_id]).length;
}
